config/routes.rb
Rails.application.routes.draw do
  root "movies#index"
  resources :movies do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

  has_many  :reviews, dependent: :destroy
  has_attached_file :image

  RATINGS = %w(G PG PG-13 R NC-17)

  validates :title, :released_on, :duration, presence: true

  validates :description, length: { minimum: 25 }

  validates :gross_earnings, numericality: { greater_than_or_equal_to: 0 }

  validates_attachment :image,
  :content_type => { :content_type => ['image/jpeg', 'image/png'] },
  :size => { :less_than => 1.megabyte }

  def flop?
    gross_earnings.blank? || gross_earnings < 50000000
  end

  def self.released
    where("released_on < ?", Time.now).order("released_on desc")
  end

  def average_stars
    reviews.average(:stars)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true

  validates :comment, length: {minimum: 4}

  STARS = [1,2,3,4,5]

  validates :stars, inclusion: {
    in: STARS,
    message: "must be between 1 and 5"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.released
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to @movie, notice: "Movie successfully updated!"
    else
      render :edit
    end
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: "Movie successfully created!"
    else
      render :new
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url, alert: "Movie successfully deleted!"
  end

private

  def movie_params
    movie_params = params.require(:movie).permit(:title, :description, :rating, :released_on, :gross_earnings, :cast, :director, :duration, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie
  def index
    @reviews = @movie.reviews
  end

  def new
    @review = @movie.reviews.new
  end

  def create
    @review = @movie.reviews.new(review_params)
    if @review.save
      redirect_to movie_reviews_path(@movie), notice: "Review posted!"
    else
      render :new
    end
  end

  def edit
    @review = @movie.reviews.find(params[:id])
  end

  def update
    @review = @movie.reviews.find(params[:id])
    if @review.update(review_params)
      redirect_to movie_reviews_path(@movie), notice: "Review successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @review = @movie.reviews.find(params[:id])
    @review.destroy
    redirect_to movie_reviews_path(@movie), notice: "Review successfully deleted."
  end

private

  def review_params
    review_params = params.require(:review).permit(:name, :location, :stars, :comment)
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, "Flop!")
    else
      number_to_currency(movie.gross_earnings)
    end
  end

  def image_for(movie)
    if movie.image.exists?
      image_tag(movie.image.url)
    else
      image_tag('placeholder.png')
    end
  end

  def format_average_stars(movie)
    if movie.average_stars.zero?
      content_tag(:strong, "No reviews yet.")
    else
      pluralize(number_with_precision(movie.average_stars, precision: 1), "star")
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>Copyright &copy 2019 <a href="https://github.com/kdbarton1s">Kayla B</a>.
  All information and pictures were pulled from <a href="https://www.imdb.com/?ref_=nv_home">IMDB</a>.</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <h1><%= link_to("Marvel Movies Watchlist", root_path) %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">


    <title>Marvel Movies Watchlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>
    <%= render "layouts/flash" %>

    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/movies/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Ope! The <%= object.class.name.titleize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <%= render "errors", object: @movie %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title, autofocus: true %>
  </p>
  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description, cols: 40, rows: 7 %>
  </p>
  <p>
    <%= f.label :rating %><br>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
  </p>
  <p>
    <%= f.label :released_on %><br>
    <%= f.date_field :released_on %>
  </p>
  <p>
    <%= f.label :gross_earnings %><br>
    <%= f.number_field :gross_earnings %>
  </p>
  <p>
    <%= f.label :cast %><br>
    <%= f.text_field :cast %>
  </p>
  <p>
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </p>
  <p>
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
    <%= image_for(@movie) %>
  </p>
  <p><%= f.submit %> | <%= link_to("Cancel", movies_path) %></p>

<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form" %>

app/views/movies/index.html.erb
<div class="container-fluid">
  <h2 id="home-page-h2"><%= pluralize(@movies.size, "Movie") %>  <span><%= link_to("Add New Movie", new_movie_path) %></span></h2>
  <% @movies.each do |movie| %>
    <div class="row">
      <div class="movie-info">
        <div class="col-md-4">
          <h3 class="movie-title-index"><%= link_to(movie.title, movie) %></h3>
          <%= image_for(movie) %>
        </div>
        <div class="col-md-6">
          <h4>Description</h4>
          <p><%= truncate(movie.description, length: 100, separator: ' ') %></p>
          <table class="table">
            <tr>
              <th>Released:</th>
              <td><%= movie.released_on %> (<%=time_ago_in_words(movie.released_on) %> ago)</td>
            </tr>
            <tr>
              <th>Rating:</th>
              <td><%= movie.rating %></td>
            </tr>
            <tr>
              <th>Total Gross:</th>
              <td> <%= format_total_gross(movie) %></td>
            </tr>
            <tr>
              <th>Duration:</th>
              <td><%=  movie.duration %></td>
            </tr>
          </table>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/movies/new.html.erb
<h1>Create Movie</h1>

<%= render "form" %>

app/views/movies/show.html.erb
<article class="show-page">
  <header class="show-page">
    <h1><%= @movie.title %></h1>
  </header>
  <h3>Average Stars</h3>
  <p><%= format_average_stars(@movie) %></p>
  <%= image_for(@movie)  %>
  <h3>Description</h3>
  <p><%= @movie.description %></p>

  <h3>Release Date</h3>
  <p><%= @movie.released_on %></p>

  <h3>Rating</h3>
  <p><%= @movie.rating %></p>

  <h3>Gross Earnings</h3>
  <p><%= format_total_gross(@movie) %></p>

  <h3>Director</h3>
  <p><%= @movie.director %></p>

  <h3>Cast</h3>
  <p><%= @movie.cast %></p>

  <h3>Duration</h3>
  <p><%= @movie.duration %></p>

</article>

<%= link_to("Edit", edit_movie_path) %> | <%= link_to("Delete", movie_path, method: :delete, data: {confirm: "Are you sure?"}) %> | <%= link_to("See #{pluralize(@movie.reviews.size, "review")}", movie_reviews_path(@movie)) %> | <%= link_to("Write Review", new_movie_review_path(@movie)) %>

app/views/reviews/_form.html.erb
<%= form_for([@movie, @review]) do |f| %>
  <%= render "movies/errors", object: @review %>
  <div class="">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
  <div class="">
    <%= f.label :stars %>
    <%= f.select :stars, Review::STARS, prompt: "Pick One" %>
  </div>
  <div class="">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>
  <%= f.submit "Post Review" %> | <%= link_to("Cancel", @movie) %>
<% end %>

app/views/reviews/edit.html.erb
<h2>Editing <%= @review.name %>'s Review of <%= @movie.title %></h2>
<%= render "form" %>

app/views/reviews/index.html.erb
<h2>Reviews for <%= link_to(@movie.title, @movie) %></h2>

<% @reviews.each do |review| %>
  <p><%= pluralize(review.stars, "star") %> by <%= review.name %>: &quot;<%= review.comment %>&quot; (<%= time_ago_in_words(review.created_at) %> ago)
  <%= link_to("Edit", edit_movie_review_path(@movie, review)) %> | <%= link_to("Delete", movie_review_path(@movie, review), method: :delete) %></p>
<% end  %>

app/views/reviews/new.html.erb
<h2>New Review for <%= @movie.title %></h2>
<%= render "form" %>